#!/bin/bash

dbase=SFW_Simple

create_missing_directories()
{
    cd ..
    if [ ! -d generated ]; then
        echo "Creating directory 'generated'" >&2
        mkdir generated
    fi
    if [ ! -d site ]; then
        echo "Creating directory 'site'" >&2
        mkdir site
    fi

    cd setup
}

copy_and_modify_default_stylesheet()
{
    sed "s|\*\*Default.*\*\*|${dbase} Demo|g" /usr/local/lib/schemafw/default.xsl > ../site/default.xsl
}

install_framework_to_site()
{
   cd ../site

   if [  -d includes ]; then
       echo "Framework already installed" >&2
   else
       ln -s /usr/local/lib/schemafw/web_includes includes
       copy_and_modify_default_stylesheet
   fi

   cd ../setup
}

prepare_generated_files()
{
    cd ../generated
    gensfw Person.gsf -c save
    cd ../setup
    cp -s ../generated/Person.sql .
    cd ../site
    cp -s ../generated/Person.srm .
}

create_database()
{
    # -r (raw) to omit tabular ouput
    # -N (--skip-column-names)
    local -a cmd=(
        information_schema
        -r
        -N
        -e "SELECT COUNT(*) FROM SCHEMATA WHERE SCHEMA_NAME='$dbase'"
    )

    local -i is_installed=$( mysql "${cmd[@]}" )
    echo $is_installed

    if [ $is_installed -eq 0 ]; then
        echo "Creating a new database"
        mysql -e "CREATE DATABASE IF NOT EXISTS $dbase"
        echo "Loading script files"
        mysql -f "${dbase}" < /usr/local/lib/SchemaServer/install/sys_procs.sql
    fi
}

create_gsfs_from_tables_in_database()
{
    local table
    local -a tables
    local -a query=(
        "SELECT TABLE_NAME"
        "FROM information_schema.TABLES"
        "WHERE SCHEMA_NAME='${dbase}'"
        "AND NOT( TABLE_NAME = 'SSYS_SESSION')"
        )

    tables=( $( mysql -BN -e "${query[@]}" ) )

    cd ../generated

    for table in "${tables[@]}"; do
        gensfw -d "${dbase}" -t "${table}" -c save
    done

    cd ../setup
    cp -s ../generated/*.sql .

    cd ../site
    cp -s ../generated/*.srm .

    cd ../setup

    
}

read_tables_from_tables()
{
    local IFS=$'\n'
    local -a tables
    local -a words
    local -i cwords
    local -a lines=( $( grep -i 'CREATE TABLE' tables.sql ) )
    IFS=$' '
    local line

    for line in "${lines[@]}"; do
        words=( $line )
        cwords="${#words[@]}"
        
        tables=( "${tables[@]}" "${words[${words}-1]}" )
    done

    echo "There are ${#tables[@]} table definitions" >&2
    printf "'\s'\n" "${tables[@]}" >&2

}

load_scripts()
{
    cd ../setup

    declare -a scripts=( $( ls --hide=tables*.sql *.sql ) )

    mysql "$dbase" < tables.sql

    for script in "${scripts[@]}"; do
        echo "Loading script file ${script}:"
        mysql "$dbase" < "${script}"
    done
}

create_missing_directories
install_framework_to_site

# create_database
# load_scripts                # Load the sole SQL script, tables.sql, prior to using gensfw

# create_gsfs_from_tables_in_database


# prepare_generated_files
# load_scripts                # reload scripts, which will now include Person.sql

