#!/bin/bash

dbase=SFW_Simple

create_missing_directories()
{
    cd ..
    if [ ! -d generated ]; then
        echo "Creating directory 'generated'" >&2
        mkdir generated
    fi
    if [ ! -d site ]; then
        echo "Creating directory 'site'" >&2
        mkdir site
    fi

    cd setup
}

copy_and_modify_default_stylesheet()
{
    sed "s|\*\*Default.*\*\*|${dbase} Demo|g" /usr/local/lib/schemafw/default.xsl > ../site/default.xsl
}

install_framework_to_site()
{
   cd ../site

   if [  -d includes ]; then
       echo "Framework already installed" >&2
   else
       ln -s /usr/local/lib/schemafw/web_includes includes
       copy_and_modify_default_stylesheet
   fi

   cd ../setup
}

create_database()
{
    # -r (raw) to omit tabular ouput
    # -N (--skip-column-names)
    local -a cmd=(
        information_schema
        -r
        -N
        -e "SELECT COUNT(*) FROM SCHEMATA WHERE SCHEMA_NAME='$dbase'"
    )

    local -i is_installed=$( mysql "${cmd[@]}" )
    echo $is_installed

    if [ $is_installed -eq 0 ]; then
        echo "Creating a new database"
        mysql -e "CREATE DATABASE IF NOT EXISTS $dbase"
        echo "Loading script files"
        mysql -f "${dbase}" < /usr/local/lib/SchemaServer/install/sys_procs.sql
    fi
}

create_generated_files()
{
    local tname
    for tname in "${@}"; do
        gensfw -d "${dbase}" -t "${tname}" -c save
    done
}

create_autoload_srm()
{
    local -a lines=(
        "\$shared : autoload_page"
        "   navigation")

    local tname
    for tname in "${@}"; do
        lines=( "${lines[@]}"
                "      target"
                "         label : ${tname}"
                "         url   : ${tname}.srm"
              )
    done

    printf "%s\n" "${lines[@]}" > autoload.srm
}

create_gsfs_from_tables_in_database()
{
    local table
    local -a tables
    local -a query=(
        "SELECT TABLE_NAME"
        "FROM information_schema.TABLES"
        "WHERE TABLE_SCHEMA='${dbase}'"
        "AND NOT( TABLE_NAME = 'SSYS_SESSION')"
        "ORDER BY CREATE_TIME"
        )

    tables=( $( mysql -BN -e "${query[*]}" ) )

    echo -n "About to process tables" >&2
    printf " '%s'" "${tables[@]}" >&2
    echo >&2

    cd ../generated
    create_generated_files "${tables[@]}"

    # for table in "${tables[@]}"; do
    #     echo "About to create '${table}.gsf'" >&2
    #     gensfw -d "${dbase}" -t "${table}" -c save
    # done

    cd ../setup
    cp -fs ../generated/*.sql .

    cd ../site
    cp -fs ../generated/*.srm .
    if [ "${#tables[@]}" -gt 1 ]; then
        create_autoload_srm "${tables[@]}"
    fi

    cd ../setup
}

load_scripts()
{
    cd ../setup

    declare -a scripts=( $( ls --hide=tables*.sql *.sql ) )

    mysql "$dbase" < tables.sql

    for script in "${scripts[@]}"; do
        echo "Loading script file ${script}:"
        mysql "$dbase" < "${script}"
    done
}

create_missing_directories
install_framework_to_site

create_database
load_scripts                # Load the sole SQL script, tables.sql, prior to using gensfw

create_gsfs_from_tables_in_database


# load_scripts                # reload scripts, which will now include Person.sql

